export const countryList = [
    'Everywhere',
    'United States',
    'Argentina',
    'Australia',
    'Bulgaria',
    'Canada',
    'Chile',
    'Colombia',
    'Croatia',
    'Czech Republic',
    'Finland',
    'France',
    'Germany',
    'Greece',
    'Hungary',
    'Iceland',
    'India',
    'Ireland',
    'Italy',
    'Japan',
    'Malaysia',
    'Mexico',
    'New Zealand',
    'Philippines',
    'Poland',
    'Portugal',
    'Puerto Rico',
    'Romania',
    'Serbia',
    'Singapore',
    'Spain',
    'Sweden',
    'Taiwan',
    'Thailand',
    'Turkey',
    'United Kingdom'
];