export const countryList = [
    {name: 'Everywhere', id: 'everywhere'},
    {name: 'United States', id: 'united-states'},
    {name: 'Argentina', id: 'argentina'},
    {name: 'Australia', id: 'australia'},
    {name: 'Bulgaria', id: 'bulgaria'},
    {name: 'Canada', id: 'canada'},
    {name: 'Chile', id: 'chile'},
    {name: 'Colombia', id: 'colombia'},
    {name: 'Croatia', id: 'croatia'},
    {name: 'Czech Republic', id: 'czech-republic'},
    {name: 'Finland', id: 'finland'},
    {name: 'France', id: 'france'},
    {name: 'Germany', id: 'germany'},
    {name: 'Greece', id: 'greece'},
    {name: 'Hungary', id: 'hungary'},
    {name: 'Iceland', id: 'iceland'},
    {name: 'India', id: 'india'},
    {name: 'Ireland', id: 'ireland'},
    {name: 'Italy', id: 'italy'},
    {name: 'Japan', id: 'japan'},
    {name: 'Malaysia', id: 'malaysia'},
    {name: 'Mexico', id: 'mexico'},
    {name: 'New Zealand', id: 'new-zealand'},
    {name: 'Philippines', id: 'philippines'},
    {name: 'Poland', id: 'poland'},
    {name: 'Portugal', id: 'portugal'},
    {name: 'Puerto Rico', id: 'puerto-rico'},
    {name: 'Romania', id: 'romania'},
    {name: 'Serbia', id: 'serbia'},
    {name: 'Singapore', id: 'singapore'},
    {name: 'Spain', id: 'spain'},
    {name: 'Sweden', id: 'sweden'},
    {name: 'Taiwan', id: 'taiwan'},
    {name: 'Thailand', id: 'thailand'},
    {name: 'Turkey', id: 'turkey'},
    {name: 'United Kingdom', id: 'united-kingdom'}
];