export const stateList = [
    {name: 'All', id: 'All'},
    {name: 'Alaska', id: 'AK'},
    {name: 'Alabama', id: 'AL'},
    {name: 'Arkansas', id: 'AR'},
    {name: 'Arizona', id: 'AZ'},
    {name: 'California', id: 'CA'},
    {name: 'Colorado', id: 'CO'},
    {name: 'Connecticut', id: 'CT'},
    {name: 'District of Colombia', id: 'DC'},
    {name: 'Delaware', id: 'DE'},
    {name: 'Florida', id: 'FL'},
    {name: 'Georgia', id: 'GA'},
    {name: 'Hawaii', id: 'HI'},
    {name: 'Iowa', id: 'IA'},
    {name: 'Idaho', id: 'ID'},
    {name: 'Illinois', id: 'IL'},
    {name: 'Indiana', id: 'IN'},
    {name: 'Kansas', id: 'KS'},
    {name: 'Kentucky', id: 'KY'},
    {name: 'Louisiana', id: 'LA'},
    {name: 'Massachusetts', id: 'MA'},
    {name: 'Maryland', id: 'MD'},
    {name: 'Maine', id: 'ME'},
    {name: 'Michigan', id: 'MI'},
    {name: 'Minnesota', id: 'MN'},
    {name: 'Missouri', id: 'MO'},
    {name: 'Mississippi', id: 'MS'},
    {name: 'Montana', id: 'MT'},
    {name: 'North Carolina', id: 'NC'},
    {name: 'North Dakota', id: 'ND'},
    {name: 'Nebraska', id: 'NE'},
    {name: 'New Hampshire', id: 'NH'},
    {name: 'New Jersey', id: 'NJ'},
    {name: 'New Mexico', id: 'NM'},
    {name: 'Nevada', id: 'NV'},
    {name: 'New York', id: 'NY'},
    {name: 'Ohio', id: 'OH'},
    {name: 'Oklahoma', id: 'OK'},
    {name: 'Oregon', id: 'OR'},
    {name: 'Pennsylvania', id: 'PA'},
    {name: 'Rhode Island', id: 'RI'},
    {name: 'South Carolina', id: 'SC'},
    {name: 'South Dakota', id: 'SD'},
    {name: 'Tennessee', id: 'TN'},
    {name: 'Texas', id: 'TX'},
    {name: 'Utah', id: 'UT'},
    {name: 'Virginia', id: 'VA'},
    {name: 'Vermont', id: 'VT'},
    {name: 'Washington', id: 'WA'},
    {name: 'Wisconsin', id: 'WI'},
    {name: 'West Virginia', id: 'WV'},
    {name: 'Wyoming', id: 'WY'}
];